name: Deploy to production

on:
  push:
    branches: ["main"]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: ["ci"]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Ansible
        run: python -m pip install ansible

      - name: Install docker module
        run: ansible-galaxy collection install community.docker

      - name: Test connection to server through `ansible.cfg`
        run: ansible all -m ping

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_github
          chmod 600 ~/.ssh/id_rsa_github
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Check for Ansible folder
        run: ls

      - name: Run Ansible Playbook (Production)
        run: ansible-playbook -i ansible/inventory.ini ansible/prod/deployment.yaml
